version: '3.7'

services:
  app:
    image: estebancortina/sw-seguro-back:1.2
    ports:
      - "443:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=prod
      - MYSQL_DATABASE=sw_seguro_prod
      - MYSQL_PASSWORD=28953ca4-1873-430a-8d30-14c9fc643aa7
      - MYSQL_PORT=3320
      - MYSQL_HOST=host.docker.internal

  db:
    image: estebancortina/sw-seguro-db:1.0
    ports:
      - "3320:3309"
    environment:
      MYSQL_DATABASE: sw_seguro_prod
      MYSQL_ROOT_PASSWORD: 28953ca4-1873-430a-8d30-14c9fc643aa7